# Generated by Django 5.2.15 on 2026-06-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='ID de session')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('cart', models.JSONField(blank=True, default=list, verbose_name='Panier')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='Écran courant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
            ],
            options={
                'verbose_name': 'Session USSD',
                'verbose_name_plural': 'Sessions USSD',
                'ordering': ['-updated_at'],
            },
        ),
    ]
