# Generated by Django 5.2.15 on 2026-06-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdsession',
            name='context',
            field=models.JSONField(blank=True, default=dict, verbose_name='Contexte'),
        ),
    ]
