# Generated by Django 5.2.15 on 2026-07-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0002_ussdsession_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ussdsession',
            name='cart',
        ),
    ]
