# Generated by Django 5.2.15 on 2026-07-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_dyu',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom (dioula)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ff',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom (peul)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ha',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom (haoussa)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_wo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom (wolof)'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text="Une alerte s'affiche dans l'admin dès que le stock atteint ce seuil.", verbose_name="Seuil d'alerte stock bas"),
        ),
        migrations.AddField(
            model_name='product',
            name='name_dyu',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom (dioula)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ff',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom (peul)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ha',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom (haoussa)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_wo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom (wolof)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom (français)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom (français)'),
        ),
    ]
