# Generated by Django 5.2.15 on 2026-07-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerussd',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('ha', 'Haoussa'), ('dyu', 'Dioula'), ('ff', 'Peul'), ('wo', 'Wolof')], default='fr', help_text='Langue choisie par le client lors de sa première session USSD.', max_length=5, verbose_name='Langue'),
        ),
    ]
