# Generated by Django 5.2.15 on 2026-07-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customerussd_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerussd',
            name='cart',
            field=models.JSONField(blank=True, default=list, verbose_name='Panier en cours'),
        ),
        migrations.AddField(
            model_name='customerussd',
            name='cart_updated_at',
            field=models.DateTimeField(blank=True, help_text='Sert à expirer les paniers abandonnés (voir USSD_CART_TTL_HOURS).', null=True, verbose_name='Panier modifié le'),
        ),
    ]
